---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  namespace: development
  labels:
    app: aws-example-octodex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aws-example-octodex
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
        - image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          imagePullPolicy: Always
          name: aws-example-octodex
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: aws-example-octodex
    namespace: development
    labels:
        app: aws-example-octodex
spec:
    type: LoadBalancer
    selector:
        app: aws-example-octodex
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 3000

---
apiVersion: v1
kind: Namespace
metadata:
    name: development