---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-node-app
  namespace: development
  labels:
    app: kubernetes-node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-node-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
    
  template:
    metadata:
      labels:
        app: kubernetes-node-app
    
    spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: eks.amazonaws.com/capacityType
              operator: In
              values:
              - SPOT
      
    containers:
    - name: kubernetes-node-app
      image: 910756530301.dkr.ecr.us-west-2.amazonaws.com/kubernetes-node-app
      imagePullPolicy: Always
      ports:
      - containerPort: 3000
        name: kubernetes-node-app

---
apiVersion: v1
kind: Service
metadata:
    name: kubernetes-node-app
    namespace: development
    labels:
        app: kubernetes-node-app
spec:
    type: LoadBalancer
    selector:
        app: kubernetes-node-app
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 3000

---
apiVersion: v1
kind: Namespace
metadata:
    name: development